import { IHeroes } from '../types'

export const heroes: IHeroes = [
  {
    name: 'nefertiti',
    role: 'ruler',
    power: 400,
    health: 900,
    stamina: 200,
    defense: 200,
    movement: 3,
  },
  {
    name: 'leonidas',
    role: 'warrior',
    power: 200,
    health: 1100,
    stamina: 200,
    movement: 2,
    defense: 300,
  },
  {
    name: 'marie_curie',
    role: 'artist',
    power: 250,
    health: 800,
    stamina: 400,
    movement: 4,
    defense: 150,
  },
  {
    name: 'da_vinci',
    role: 'artist',
    power: 150,
    health: 800,
    stamina: 450,
    movement: 4,
    defense: 150,
  },
  {
    name: 'attila',
    role: 'ruler',
    power: 300,
    health: 850,
    stamina: 250,
    movement: 3,
    defense: 300,
  },
  {
    name: 'sun_tzu',
    role: 'thinker',
    power: 300,
    health: 750,
    stamina: 350,
    movement: 4,
    defense: 200,
  },
  {
    name: 'isabel_i',
    role: 'ruler',
    power: 450,
    health: 800,
    stamina: 200,
    movement: 4,
    defense: 150,
  },
  {
    name: 'bach',
    role: 'artist',
    power: 150,
    health: 750,
    stamina: 500,
    movement: 4,
    defense: 200,
  },
  {
    name: 'cleopatra',
    role: 'ruler',
    power: 600,
    health: 600,
    stamina: 300,
    movement: 3,
    defense: 200,
  },
]
