import { IHeroes } from '../types'
import { attack, fireRange, heal, rulerBuff, warriorBuff } from './attacks'

export const heroes: IHeroes = {
  nefertiti: {
    name: 'Nefertiti',
    img: 'nefertiti',
    role: 'ruler',
    power: 400,
    health: 600,
    stamina: 200,
    movement: 3,
    defense: 500,
    attacks: [attack, fireRange],
  },
  leonidas: {
    name: 'Leonidas',
    img: 'leonidas',
    role: 'warrior',
    power: 200,
    health: 750,
    stamina: 200,
    movement: 2,
    defense: 650,
    attacks: [attack, warriorBuff],
  },
  mariCurie: {
    name: 'Marie Curie',
    img: 'mariCurie',
    role: 'artist',
    power: 250,
    health: 550,
    stamina: 300,
    movement: 3,
    defense: 550,
    attacks: [attack, heal],
  },
  daVinci: {
    name: 'Da Vinci',
    img: 'daVinci',
    role: 'artist',
    power: 150,
    health: 750,
    stamina: 200,
    movement: 4,
    defense: 500,
    attacks: [attack, heal],
  },
  bach: {
    name: 'Bach',
    img: 'bach',
    role: 'artist',
    power: 150,
    health: 750,
    stamina: 200,
    movement: 4,
    defense: 500,
    attacks: [attack, heal],
  },
  attila: {
    name: 'Attila',
    img: 'attila',
    role: 'warrior',
    power: 200,
    health: 700,
    stamina: 300,
    movement: 3,
    defense: 500,
    attacks: [attack, rulerBuff],
  },
  isabel: {
    name: 'Isabel I',
    img: 'isabel',
    role: 'ruler',
    power: 450,
    health: 450,
    stamina: 200,
    movement: 2,
    defense: 700,
    attacks: [attack, rulerBuff],
  },
  cleopatra: {
    name: 'Cleopatra',
    img: 'cleopatra',
    role: 'ruler',
    power: 600,
    health: 400,
    stamina: 200,
    movement: 3,
    defense: 500,
    attacks: [attack, rulerBuff],
  },
  sunTzu: {
    name: 'Sun Tzu',
    img: 'sunTzu',
    role: 'thinker',
    power: 250,
    health: 550,
    stamina: 300,
    movement: 3,
    defense: 550,
    attacks: [attack, fireRange],
  },
}
